(() => {
  const translations = {
    'Saltar para o conteúdo': 'Skip to content',
    'Espaços': 'Spaces',
    'Restaurante': 'Restaurant',
    'Menus': 'Menus',
    'Eventos': 'Events',
    'Galeria': 'Gallery',
    'Visite-nos': 'Visit us',
    'Reservar': 'Book a table',
    'Sobre': 'About',
    'Contactos': 'Contact',
    'Reservas': 'Reservations',
    'MAPUTO · À BEIRA-MAR': 'MAPUTO · BY THE SEA',
    'O Índico': 'The Indian Ocean',
    'marca o ritmo.': 'sets the pace.',
    'Boa mesa, brisa do mar e espaço para estar junto. Bem-vindo ao South Beach.': 'Good food, sea air and room to be together. Welcome to South Beach.',
    'Faça uma reserva': 'Book a table',
    'Descubra o espaço': 'Explore the venue',
    'UM LUGAR, VÁRIOS MOMENTOS': 'ONE PLACE, MANY MOMENTS',
    'SOUTH BEACH · MAPUTO': 'SOUTH BEACH · MAPUTO',
    'Mais do que': 'More than',
    'um destino.': 'a destination.',
    'Um lugar para saborear, celebrar e estar junto ao Índico.': 'A place to savour, celebrate and come together by the Indian Ocean.',
    'Encontros que': 'Gatherings that',
    'ficam': 'stay',
    'na memória.': 'with you.',
    'À beira do Índico, cada visita tem o seu próprio ritmo. Venha para uma refeição tranquila, um cocktail ao fim da tarde ou para acompanhar o jogo com os amigos.': 'On the shores of the Indian Ocean, every visit has its own pace. Come for a relaxed meal, an evening cocktail or a game with friends.',
    'Conheça o South Beach': 'Discover South Beach',
    'ESCOLHA O SEU MOMENTO': 'CHOOSE YOUR MOMENT',
    'Três formas': 'Three ways',
    'de': 'to',
    'viver South Beach.': 'experience South Beach.',
    'Um destino à beira-mar, com ambientes para diferentes momentos do dia.': 'A seaside destination with spaces for every part of the day.',
    'SABORES DO ÍNDICO': 'FLAVOURS OF THE INDIAN OCEAN',
    'Uma mesa para explorar sabores, partilhar pratos e prolongar a conversa.': 'A table for discovering flavours, sharing dishes and lingering over good conversation.',
    'Descobrir': 'Discover',
    'BRISA & COCKTAILS': 'SEA BREEZE & COCKTAILS',
    'Restaurante · Beach Bar · Sports Bar': 'Restaurant · Beach Bar · Sports Bar',
    'Beach Bar · South Beach Maputo': 'Beach Bar · South Beach Maputo',
    'Eventos · South Beach Maputo': 'Events · South Beach Maputo',
    'Galeria · South Beach Maputo': 'Gallery · South Beach Maputo',
    'Restaurante · South Beach Maputo': 'Restaurant · South Beach Maputo',
    'Sports Bar · South Beach Maputo': 'Sports Bar · South Beach Maputo',
    'South Beach · Moçambique': 'South Beach · Mozambique',
    'Tapas, sushi': 'Tapas, sushi',
    'Café · 08h00–10h00': 'Breakfast · 08:00–10:00',
    'Almoço · 12h00–14h00': 'Lunch · 12:00–14:00',
    '17h00–19h00': '17:00–19:00',
    'Jantar · 20h00–21h30': 'Dinner · 20:00–21:30',
    '17h00–19h00 · Jantar · 20h00–21h30': '17:00–19:00 · Dinner · 20:00–21:30',
    'Maputo, Moçambique': 'Maputo, Mozambique',
    'MOÇAMBIQUE': 'MOZAMBIQUE',
    'Petiscos, bebidas e aquele tempo extra que sabe bem junto ao mar.': 'Small plates, drinks and a little extra time by the sea.',
    'JOGO, COMIDA & AMIGOS': 'SPORTS, FOOD & FRIENDS',
    'Junte a sua equipa, escolha o lugar e aproveite o ambiente de jogo.': 'Gather your team, find your spot and enjoy the game-day atmosphere.',
    'Explorar': 'Explore',
    'FRESCO · LOCAL · À BEIRA-MAR': 'FRESH · LOCAL · BY THE SEA',
    'DA COZINHA PARA A MESA': 'FROM THE KITCHEN TO THE TABLE',
    'Sabores que': 'Flavours that',
    'pedem': 'invite you to',
    'mais tempo.': 'stay a little longer.',
    'Frutos do mar, pratos para partilhar e cocktails preparados para acompanhar o momento. Descubra os menus do restaurante, do beach bar e do sports bar.': 'Seafood, dishes made for sharing and cocktails for the moment. Explore the restaurant, beach bar and sports bar menus.',
    'Menu do restaurante': 'Restaurant menu',
    'Menu do beach bar': 'Beach bar menu',
    'Menu do sports bar': 'Sports bar menu',
    'CELEBRE À SUA MANEIRA': 'CELEBRATE YOUR WAY',
    'Os melhores': 'The best',
    'momentos são': 'moments are',
    'partilhados.': 'shared.',
    'Um cenário especial para reunir pessoas, celebrar ocasiões ou simplesmente aproveitar um dia diferente junto ao mar.': 'A special setting to bring people together, celebrate an occasion or enjoy a different day by the sea.',
    'Descubra os eventos': 'Explore events',
    'UM OLHAR PELO ESPAÇO': 'A LOOK AROUND',
    'Sinta o': 'Feel the',
    'ambiente.': 'atmosphere.',
    'Ver galeria completa': 'View the full gallery',
    'A SUA MESA ESTÁ À ESPERA': 'YOUR TABLE IS WAITING',
    'Encontramo-nos': 'Shall we meet',
    'à beira-mar?': 'by the sea?',
    'Reservar uma mesa': 'Book a table',
    'VISITE-NOS': 'VISIT US',
    'Ver localização': 'View location',
    'CONTACTO': 'CONTACT',
    'HORÁRIOS DE REFEIÇÃO': 'DINING HOURS',
    'HORÁRIOS DE REFEIÇÃO PUBLICADOS': 'PUBLISHED DINING HOURS',
    'Confirme a disponibilidade ao reservar.': 'Please confirm availability when booking.',
    'Os horários podem mudar. Confirme antes de se deslocar.': 'Opening hours may change. Please confirm before visiting.',
    'SOUTH BEACH · MAPUTO': 'SOUTH BEACH · MAPUTO',
    'O ESPÍRITO SOUTH BEACH': 'THE SOUTH BEACH SPIRIT',
    'ENCONTROS À BEIRA-MAR': 'SEASIDE GATHERINGS',
    'Um espaço feito para': 'A place made for',
    'bons momentos.': 'good moments.',
    'O South Beach reúne restaurante, beach bar e sports bar num só destino à beira-mar em Maputo. Cada espaço oferece uma forma diferente de aproveitar a visita, sempre com tempo para boa comida e bons encontros.': 'South Beach brings a restaurant, beach bar and sports bar together in one seaside destination in Maputo. Each space offers a different way to enjoy your visit, with good food and good company at its heart.',
    'Venha para uma refeição, um cocktail, uma partida de bilhar ou um evento especial. Escolha o seu momento e encontre o seu lugar.': 'Come for a meal, a cocktail, a game of pool or a special event. Choose your moment and find your place.',
    'Planeie a sua visita': 'Plan your visit',
    'TRÊS ESPAÇOS, UM DESTINO': 'THREE SPACES, ONE DESTINATION',
    'À sua maneira.': 'Your way.',
    'Ao seu ritmo.': 'At your own pace.',
    'Explore os espaços': 'Explore the spaces',
    'A IDEIA POR TRÁS DO ENCONTRO': 'THE IDEA BEHIND THE GATHERING',
    'Um ritmo.': 'One rhythm.',
    'Três formas de estar.': 'Three ways to be.',
    '01 / O LUGAR': '01 / THE PLACE',
    'À beira do Índico': 'By the Indian Ocean',
    'A Marginal de Maputo é o cenário para chegar, respirar e aproveitar o momento.': 'Maputo’s Marginal is the setting to arrive, take a breath and enjoy the moment.',
    '02 / À MESA': '02 / AT THE TABLE',
    'Sabores para partilhar': 'Flavours to share',
    'Escolha o seu espaço, descubra o menu e deixe a refeição ganhar o seu próprio ritmo.': 'Choose your space, explore the menu and let the meal find its own pace.',
    '03 / JUNTOS': '03 / TOGETHER',
    'Momentos em comum': 'Moments together',
    'Um almoço, um jogo ou uma celebração: há sempre uma boa razão para reunir pessoas.': 'A lunch, a game or a celebration: there is always a good reason to bring people together.',
    'BRISA & COCKTAILS': 'SEA BREEZE & COCKTAILS',
    'Beach Bar': 'Beach Bar',
    'by the sea.': 'by the sea.',
    'Petiscos, bebidas e bons momentos à beira-mar.': 'Small plates, drinks and good moments by the sea.',
    'Ver menu': 'View menu',
    'UM MOMENTO MAIS LEVE': 'A MORE RELAXED MOMENT',
    'Brinde ao': 'Raise a glass to',
    'tempo junto.': 'time together.',
    'Faça uma pausa, partilhe tapas ou escolha um cocktail para acompanhar o fim da tarde. O Beach Bar é o espaço para aproveitar o ambiente e deixar a conversa continuar.': 'Take a break, share tapas or choose a cocktail for the late afternoon. The Beach Bar is a place to enjoy the atmosphere and let the conversation carry on.',
    'Consultar o menu completo': 'View the full menu',
    'PETISCOS · SUSHI · COCKTAILS': 'SMALL PLATES · SUSHI · COCKTAILS',
    'Escolha o seu': 'Choose your',
    'próximo brinde.': 'next drink.',
    'Explore as opções de tapas, sushi, bebidas e cocktails no menu actual do South Beach.': 'Explore tapas, sushi, drinks and cocktails on the current South Beach menu.',
    'Explorar o menu': 'Explore the menu',
    'À BEIRA-MAR, À SUA MANEIRA': 'BY THE SEA, YOUR WAY',
    'Guarde um lugar': 'Save a place',
    'para si.': 'for yourself.',
    'Fazer reserva': 'Make a reservation',
    'À SUA ESPERA EM MAPUTO': 'WAITING FOR YOU IN MAPUTO',
    'Venha pelo': 'Take the',
    'caminho do mar.': 'seaside route.',
    'PLANEIE A VISITA': 'PLAN YOUR VISIT',
    'Estamos à': 'We are',
    'sua espera.': 'waiting for you.',
    'ENDEREÇO': 'ADDRESS',
    'Obter direcções': 'Get directions',
    'Abrir no Google Maps': 'Open in Google Maps',
    'Quer escolher uma data antes de vir?': 'Would you like to choose a date before you visit?',
    'MOMENTOS PARA PARTILHAR': 'MOMENTS TO SHARE',
    'Vemo-nos': 'See you',
    'no próximo evento.': 'at the next event.',
    'Descubra o que está a acontecer no South Beach.': 'Find out what is happening at South Beach.',
    'AGENDA': 'WHAT’S ON',
    'Sem eventos anunciados': 'No events announced',
    'neste momento.': 'at this time.',
    'Consulte esta página novamente ou acompanhe os canais oficiais do South Beach para novidades. Enquanto isso, veja alguns momentos de eventos anteriores.': 'Check this page again or follow South Beach’s official channels for updates. In the meantime, revisit some moments from past events.',
    'Ver galeria de eventos passados': 'View the past events gallery',
    'ARQUIVO': 'ARCHIVE',
    'Momentos que': 'Moments that',
    'ficaram.': 'stay with us.',
    'Abrir a galeria': 'Open the gallery',
    'EVENTOS PRIVADOS': 'PRIVATE EVENTS',
    'Vamos criar': 'Let’s create',
    'um momento seu.': 'a moment of your own.',
    'Fale com a equipa sobre a sua ocasião. Ao enviar o formulário, o seu programa de email abrirá uma mensagem pré-preenchida para revisão.': 'Tell our team about your occasion. Submitting the form will open a pre-filled email for you to review.',
    'Nome': 'Name',
    'Email': 'Email',
    'Tipo de ocasião': 'Occasion type',
    'Seleccione': 'Select',
    'Aniversário': 'Birthday',
    'Evento corporativo': 'Corporate event',
    'Casamento': 'Wedding',
    'Outra ocasião': 'Other occasion',
    'Data preferida': 'Preferred date',
    'Conte-nos um pouco mais': 'Tell us a little more',
    'Preparar pedido': 'Prepare request',
    'Este formulário abre um rascunho no seu programa de email. O pedido só é enviado quando confirmar o envio.': 'This form opens a draft in your email app. Your request is sent only after you confirm and send it.',
    'Um lugar cheio': 'A place full',
    'de momentos.': 'of moments.',
    'Explore o South Beach e recorde eventos anteriores.': 'Explore South Beach and revisit past events.',
    'IMAGENS SOUTH BEACH': 'SOUTH BEACH IMAGES',
    'Descubra o': 'Discover the',
    'ambiente.': 'atmosphere.',
    'Seleccione uma imagem para ampliar. Use as setas do teclado ou os controlos para percorrer a galeria.': 'Select an image to enlarge it. Use your keyboard arrows or the controls to browse the gallery.',
    'Tudo': 'All',
    'Espaços': 'Spaces',
    'Eventos passados': 'Past events',
    'South Beach · Espaço': 'South Beach · Venue',
    'Restaurante': 'Restaurant',
    '6.º Aniversário': '6th Anniversary',
    'Réveillon': 'New Year’s Eve',
    'Quer viver o seu próprio momento?': 'Ready to create your own moment?',
    'Planear uma visita': 'Plan a visit',
    'DA COZINHA PARA A MESA': 'FROM THE KITCHEN TO THE TABLE',
    'Encontre o seu': 'Find your',
    'próximo sabor.': 'next favourite flavour.',
    'Escolha o espaço e consulte o menu completo.': 'Choose a space and view its full menu.',
    'TRÊS MENUS, UM DESTINO': 'THREE MENUS, ONE DESTINATION',
    'O que lhe': 'What are you',
    'apetece hoje?': 'in the mood for today?',
    'Os menus e preços completos são mantidos nas páginas actuais do South Beach. Abra a área pretendida para consultar a versão publicada.': 'Full menus and prices are maintained on South Beach’s current pages. Choose a space to view the published menu.',
    'MENU DO RESTAURANTE': 'RESTAURANT MENU',
    'Sabores do mar': 'Flavours of the sea',
    'e muito mais.': 'and much more.',
    'À la carte': 'À la carte',
    'Sushi': 'Sushi',
    'Tapas': 'Tapas',
    'Bebidas': 'Drinks',
    'Cocktails': 'Cocktails',
    'Abrir menu completo': 'Open full menu',
    'MENU DO BEACH BAR': 'BEACH BAR MENU',
    'e cocktails.': 'and cocktails.',
    'MENU DO SPORTS BAR': 'SPORTS BAR MENU',
    'Petiscos para': 'Small plates for',
    'ver o jogo.': 'game time.',
    'Petiscos': 'Small plates',
    'Pizzas': 'Pizzas',
    'Pregos': 'Steak sandwiches',
    'Hambúrgueres': 'Burgers',
    'Wraps': 'Wraps',
    'Disponibilidade, ingredientes e preços podem mudar. Confirme os detalhes no menu actual ou contacte directamente o South Beach.': 'Availability, ingredients and prices may change. Check the current menu or contact South Beach directly.',
    'RESERVAS · SOUTH BEACH MAPUTO': 'RESERVATIONS · SOUTH BEACH MAPUTO',
    'Escolha a data.': 'Choose your date.',
    'Nós tratamos da mesa.': 'We’ll take care of the table.',
    'Use o sistema de reservas actual do South Beach para indicar o tamanho do grupo, a data e o horário pretendidos. A disponibilidade e a confirmação são feitas directamente pela equipa do espaço.': 'Use South Beach’s current booking system to choose your group size, date and preferred time. Availability and confirmation are handled by the venue team.',
    'Continuar para reservas': 'Continue to reservations',
    'A reserva será concluída na página oficial do South Beach.': 'Your reservation will be completed on the official South Beach page.',
    'PRECISA DE AJUDA?': 'NEED HELP?',
    'SABORES DO ÍNDICO': 'FLAVOURS OF THE INDIAN OCEAN',
    'Restaurante': 'Restaurant',
    'South Beach.': 'South Beach.',
    'Pratos para partilhar e refeições para saborear sem pressa.': 'Dishes to share and meals to savour at your own pace.',
    'À MESA': 'AT THE TABLE',
    'Frescor tropical.': 'Tropical freshness.',
    'Sabores do mar.': 'Flavours of the sea.',
    'O menu do restaurante combina saladas, peixe grelhado e frutos do mar com influências de várias cozinhas. É uma mesa para uma refeição a dois, um almoço em família ou um jantar que se prolonga.': 'The restaurant menu pairs salads, grilled fish and seafood with influences from many kitchens. It is a table for a meal for two, a family lunch or a dinner that lingers.',
    'Consultar o menu completo': 'View the full menu',
    'Pratos quentes, saladas e especialidades para explorar.': 'Hot dishes, salads and specialities to explore.',
    'Sushi & tapas': 'Sushi & tapas',
    'Opções para partilhar e combinar à mesa.': 'Options to share and enjoy together.',
    'Bebidas & cocktails': 'Drinks & cocktails',
    'Escolha algo para acompanhar a refeição.': 'Choose something to accompany your meal.',
    'A SUA MESA ESPERA POR SI': 'YOUR TABLE IS WAITING',
    'Vamos reservar': 'Shall we reserve',
    'um lugar?': 'a place?',
    'JOGO · COMIDA · AMIGOS': 'SPORTS · FOOD · FRIENDS',
    'O jogo é': 'The game is',
    'mais divertido junto.': 'better together.',
    'Reúna a equipa e aproveite o ambiente do Sports Bar.': 'Bring your team together and enjoy the Sports Bar atmosphere.',
    'JUNTE-SE À CONVERSA': 'JOIN THE CONVERSATION',
    'Torça, jogue': 'Cheer, play',
    'e partilhe.': 'and share.',
    'O Sports Bar junta comida, bebidas e o ambiente dos grandes jogos. E quando quiser trocar a bancada pelo desafio, pode testar a sua pontaria na mesa de bilhar.': 'The Sports Bar brings together food, drinks and the atmosphere of the big games. When you are ready to trade the stands for a challenge, test your aim at the pool table.',
    'Ver a página actual do Sports Bar': 'Visit the current Sports Bar page',
    'Desafie os amigos numa partida de bilhar.': 'Challenge your friends to a game of pool.',
    'Encontre o seu lugar, peça algo para beber e aproveite.': 'Find your seat, order a drink and enjoy.',
    'Comida para partilhar': 'Food to share',
    'Petiscos, pizzas, pregos, hambúrgueres e wraps no menu actual.': 'Small plates, pizzas, steak sandwiches, burgers and wraps on the current menu.',
    'A EQUIPA ESTÁ À SUA ESPERA': 'THE TEAM IS WAITING FOR YOU',
    'Veja o jogo': 'Watch the game',
    'connosco.': 'with us.',
    'SOUTH BEACH — início': 'South Beach — home',
    'Abrir menu': 'Open menu',
    'Fechar menu': 'Close menu',
    'Navegação principal': 'Main navigation',
    'Escolha um espaço': 'Choose a space',
    'Filtrar menu por categoria': 'Filter menu by category',
    'Comida': 'Food',
    'Imagem da galeria': 'Gallery image',
    'Imagem ampliada da galeria': 'Enlarged gallery image',
    'Fechar imagem': 'Close image',
    'Imagem anterior': 'Previous image',
    'Imagem seguinte': 'Next image',
    'Ambiente do South Beach': 'South Beach atmosphere',
    'Ambiente do restaurante South Beach': 'South Beach restaurant atmosphere',
    'Espaço exterior do South Beach': 'South Beach outdoor area',
    'Ambiente do sports bar South Beach': 'South Beach sports bar atmosphere',
    'Prato servido no South Beach': 'A dish served at South Beach',
    'Vista e ambiente do South Beach': 'South Beach views and atmosphere',
    'Restaurante South Beach': 'South Beach restaurant',
    'Espaço exterior South Beach': 'South Beach outdoor area',
    'Sports bar South Beach': 'South Beach sports bar',
    'Vista do South Beach': 'View of South Beach'
  };

  const titles = {
    'South Beach Maputo — Restaurante, Beach Bar & Sports Bar': 'South Beach Maputo — Restaurant, Beach Bar & Sports Bar',
    'Sobre o South Beach — Maputo': 'About South Beach — Maputo',
    'Restaurante — South Beach Maputo': 'Restaurant — South Beach Maputo',
    'Beach Bar — South Beach Maputo': 'Beach Bar — South Beach Maputo',
    'Sports Bar — South Beach Maputo': 'Sports Bar — South Beach Maputo',
    'Menus — South Beach Maputo': 'Menus — South Beach Maputo',
    'Eventos — South Beach Maputo': 'Events — South Beach Maputo',
    'Galeria — South Beach Maputo': 'Gallery — South Beach Maputo',
    'Contactos e localização — South Beach Maputo': 'Contact & location — South Beach Maputo',
    'Reservas — South Beach Maputo': 'Reservations — South Beach Maputo'
  };
  const descriptions = {
    'Descubra o restaurante, o beach bar, o sports bar e os eventos do South Beach, na Marginal de Maputo.': 'Discover the restaurant, beach bar, sports bar and events at South Beach on Maputo’s Marginal.',
    'Conheça o South Beach, um espaço de encontro à beira-mar em Maputo.': 'Discover South Beach, a seaside meeting place in Maputo.',
    'Descubra o restaurante South Beach em Maputo e consulte o menu actual.': 'Discover the South Beach restaurant in Maputo and view the current menu.',
    'Descubra o Beach Bar do South Beach em Maputo.': 'Discover the South Beach Beach Bar in Maputo.',
    'Descubra o Sports Bar do South Beach em Maputo.': 'Discover the South Beach Sports Bar in Maputo.',
    'Explore os menus actuais do restaurante, beach bar e sports bar do South Beach.': 'Explore the current restaurant, beach bar and sports bar menus at South Beach.',
    'Veja eventos e informações sobre eventos privados no South Beach, Maputo.': 'Explore events and private event information at South Beach, Maputo.',
    'Veja imagens do South Beach e de eventos realizados em Maputo.': 'View images of South Beach and past events in Maputo.',
    'Encontre a localização, os contactos e os horários do South Beach em Maputo.': 'Find South Beach’s location, contact details and opening hours in Maputo.',
    'Consulte as opções oficiais para reservar uma mesa no South Beach, Maputo.': 'View the official options for booking a table at South Beach, Maputo.'
  };

  const originalNodes = [];
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  let node;
  while ((node = walker.nextNode())) {
    const text = node.nodeValue.trim();
    if (translations[text]) originalNodes.push({ node, original: node.nodeValue, text });
  }
  const originalAttributes = [];
  document.querySelectorAll('[aria-label], [alt], [placeholder], [title]').forEach((element) => {
    ['aria-label', 'alt', 'placeholder', 'title'].forEach((name) => {
      const value = element.getAttribute(name);
      if (value && translations[value]) originalAttributes.push({ element, name, value });
    });
  });
  const originalTitle = document.title;
  const description = document.querySelector('meta[name="description"]');
  const originalDescription = description?.content || '';

  function applyLanguage(language) {
    originalNodes.forEach(({ node, original, text }) => {
      const leading = original.match(/^\s*/)?.[0] || '';
      const trailing = original.match(/\s*$/)?.[0] || '';
      node.nodeValue = `${leading}${language === 'en' ? translations[text] : text}${trailing}`;
    });
    originalAttributes.forEach(({ element, name, value }) => {
      element.setAttribute(name, language === 'en' ? translations[value] : value);
    });
    document.documentElement.lang = language === 'en' ? 'en' : 'pt-MZ';
    document.title = language === 'en' ? (titles[originalTitle] || originalTitle) : originalTitle;
    if (description) description.content = language === 'en' ? (descriptions[originalDescription] || originalDescription) : originalDescription;
    document.querySelectorAll('[data-language-toggle]').forEach((button) => {
      button.textContent = language === 'en' ? 'PT' : 'EN';
      button.setAttribute('aria-label', language === 'en' ? 'Switch to Portuguese' : 'Switch to English');
      button.setAttribute('aria-pressed', String(language === 'en'));
    });
    const menuButton = document.querySelector('.menu-toggle');
    if (menuButton) {
      const isOpen = menuButton.getAttribute('aria-expanded') === 'true';
      menuButton.setAttribute('aria-label', language === 'en'
        ? (isOpen ? 'Close menu' : 'Open menu')
        : (isOpen ? 'Fechar menu' : 'Abrir menu'));
    }
    try { localStorage.setItem('southBeachLanguage', language); } catch (_) {}
  }

  let language = 'pt';
  try { language = localStorage.getItem('southBeachLanguage') === 'en' ? 'en' : 'pt'; } catch (_) {}
  applyLanguage(language);
  document.querySelectorAll('[data-language-toggle]').forEach((button) => {
    button.addEventListener('click', () => applyLanguage(language = language === 'pt' ? 'en' : 'pt'));
  });
})();
