-- Dishes and drinks shown on the menus page, per space (restaurant, beach bar, sports bar) and in display order.
-- price_cents is in centavos of MZN; empty means "no price shown".
CREATE TABLE menu_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue VARCHAR(12) NOT NULL,
    kind VARCHAR(8) NOT NULL,
    section_pt VARCHAR(80) NOT NULL,
    section_en VARCHAR(80),
    name_pt VARCHAR(120) NOT NULL,
    name_en VARCHAR(120),
    description_pt VARCHAR(400),
    description_en VARCHAR(400),
    price_cents BIGINT,
    position INTEGER NOT NULL,
    visible BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_menu_venue CHECK (venue IN ('RESTAURANT', 'BEACH', 'SPORTS')),
    CONSTRAINT chk_menu_kind CHECK (kind IN ('FOOD', 'DRINKS')),
    CONSTRAINT chk_menu_price CHECK (price_cents IS NULL OR price_cents >= 0)
);
CREATE INDEX idx_menu_items_venue_position ON menu_items (venue, position);
