-- Menu divisions (the tabs: À Lá Carte, Sushi, Tapas, Bebidas, Cocktails) become records of their own, per space and in display order,
-- so staff can create them, rename them and choose the order. Items point to their division.
CREATE TABLE menu_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue VARCHAR(12) NOT NULL,
    name_pt VARCHAR(60) NOT NULL,
    name_en VARCHAR(60),
    position INTEGER NOT NULL,
    CONSTRAINT chk_menu_group_venue CHECK (venue IN ('RESTAURANT', 'BEACH', 'SPORTS')),
    CONSTRAINT uq_menu_group_name UNIQUE (venue, name_pt)
);

INSERT INTO menu_groups (venue, name_pt, name_en, position)
SELECT venue, group_pt, MAX(group_en), ROW_NUMBER() OVER (PARTITION BY venue ORDER BY MIN(position))
FROM menu_items WHERE group_pt IS NOT NULL GROUP BY venue, group_pt;

ALTER TABLE menu_items ADD COLUMN group_id BIGINT;
ALTER TABLE menu_items ADD CONSTRAINT fk_menu_item_group FOREIGN KEY (group_id) REFERENCES menu_groups (id);
UPDATE menu_items SET group_id = (SELECT g.id FROM menu_groups g WHERE g.venue = menu_items.venue AND g.name_pt = menu_items.group_pt)
WHERE group_pt IS NOT NULL;
ALTER TABLE menu_items DROP COLUMN group_pt;
ALTER TABLE menu_items DROP COLUMN group_en;
CREATE INDEX idx_menu_items_group ON menu_items (group_id);
