-- Archive of past events: details and a photo album for each. Dates are free text ("11 de Maio de 2024") because some old events
-- only ever had a day and month. image URLs are https addresses or uploaded files (/api/media/{id}).
CREATE TABLE past_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(90) NOT NULL,
    title_pt VARCHAR(120) NOT NULL,
    title_en VARCHAR(120),
    date_text_pt VARCHAR(80),
    date_text_en VARCHAR(80),
    time_text VARCHAR(60),
    location VARCHAR(120),
    description_pt VARCHAR(2000),
    description_en VARCHAR(2000),
    cover_url VARCHAR(500),
    position INTEGER NOT NULL,
    visible BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_past_events_slug UNIQUE (slug)
);

CREATE TABLE past_event_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    image_url VARCHAR(500) NOT NULL,
    position INTEGER NOT NULL,
    CONSTRAINT fk_past_event_photos_event FOREIGN KEY (event_id) REFERENCES past_events (id) ON DELETE CASCADE
);
CREATE INDEX idx_past_event_photos_event ON past_event_photos (event_id, position);
