-- Door staff: accounts that can only read and admit tickets. Created by the admin; the code is shown once and stored hashed.
-- event_id (optional) ties the account to one event; valid_until (optional) makes it expire by itself.
CREATE TABLE gate_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(40) NOT NULL,
    label VARCHAR(80) NOT NULL,
    password_hash VARCHAR(100) NOT NULL,
    event_id BIGINT,
    active BOOLEAN NOT NULL,
    valid_until TIMESTAMP WITH TIME ZONE,
    last_used_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_gate_users_username UNIQUE (username),
    CONSTRAINT fk_gate_users_event FOREIGN KEY (event_id) REFERENCES events (id)
);
