CREATE TABLE reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(20) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    requested_date DATE NOT NULL,
    requested_time TIME NOT NULL,
    party_size INTEGER NOT NULL,
    venue VARCHAR(24) NOT NULL,
    occasion VARCHAR(100),
    notes VARCHAR(1000),
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_reservations_reference UNIQUE (reference),
    CONSTRAINT chk_reservations_party_size CHECK (party_size BETWEEN 1 AND 100),
    CONSTRAINT chk_reservations_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CANCELLED')),
    CONSTRAINT chk_reservations_venue CHECK (venue IN ('RESTAURANT', 'BEACH_BAR', 'SPORTS_BAR', 'NO_PREFERENCE'))
);

CREATE INDEX idx_reservations_status_date ON reservations (status, requested_date, requested_time);
CREATE INDEX idx_reservations_created_at ON reservations (created_at DESC);
