CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(80) NOT NULL,
    title VARCHAR(150) NOT NULL,
    description VARCHAR(2000),
    location VARCHAR(150) NOT NULL,
    starts_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ends_at TIMESTAMP WITH TIME ZONE,
    status VARCHAR(16) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_events_slug UNIQUE (slug),
    CONSTRAINT chk_events_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'CANCELLED'))
);

-- Prices are stored in centavos (minor units) of MZN. capacity - sold - held is the stock still available.
CREATE TABLE ticket_types (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events (id),
    name VARCHAR(80) NOT NULL,
    description VARCHAR(500),
    price_minor BIGINT NOT NULL,
    capacity INTEGER NOT NULL,
    sold INTEGER NOT NULL DEFAULT 0,
    held INTEGER NOT NULL DEFAULT 0,
    sale_starts_at TIMESTAMP WITH TIME ZONE,
    sale_ends_at TIMESTAMP WITH TIME ZONE,
    max_per_order INTEGER NOT NULL DEFAULT 10,
    CONSTRAINT chk_ticket_types_price CHECK (price_minor >= 0),
    CONSTRAINT chk_ticket_types_stock CHECK (sold >= 0 AND held >= 0 AND sold + held <= capacity),
    CONSTRAINT chk_ticket_types_max CHECK (max_per_order BETWEEN 1 AND 50)
);
CREATE INDEX idx_ticket_types_event ON ticket_types (event_id);

CREATE TABLE ticket_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(20) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    email VARCHAR(120),
    total_minor BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(16) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_ticket_orders_reference UNIQUE (reference),
    CONSTRAINT chk_ticket_orders_status CHECK (status IN ('PENDING', 'PAID', 'EXPIRED', 'CANCELLED'))
);
CREATE INDEX idx_ticket_orders_status_expiry ON ticket_orders (status, expires_at);

CREATE TABLE ticket_order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES ticket_orders (id),
    ticket_type_id BIGINT NOT NULL REFERENCES ticket_types (id),
    quantity INTEGER NOT NULL,
    unit_price_minor BIGINT NOT NULL,
    CONSTRAINT chk_ticket_order_items_quantity CHECK (quantity > 0)
);
CREATE INDEX idx_ticket_order_items_order ON ticket_order_items (order_id);
