-- access_token opens the customer's ticket page; it is random, unguessable and never shown to other customers.
ALTER TABLE ticket_orders ADD COLUMN access_token VARCHAR(40);
CREATE UNIQUE INDEX uk_ticket_orders_access_token ON ticket_orders (access_token);

-- One row per admitted person. code is the random value encoded in the QR; it carries no personal data.
CREATE TABLE issued_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES ticket_orders (id),
    ticket_type_id BIGINT NOT NULL REFERENCES ticket_types (id),
    event_id BIGINT NOT NULL REFERENCES events (id),
    code VARCHAR(40) NOT NULL,
    status VARCHAR(12) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    used_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_issued_tickets_code UNIQUE (code),
    CONSTRAINT chk_issued_tickets_status CHECK (status IN ('VALID', 'USED', 'VOID'))
);
CREATE INDEX idx_issued_tickets_order ON issued_tickets (order_id);
CREATE INDEX idx_issued_tickets_event ON issued_tickets (event_id, status);
