-- Editable website content. Keys come from data-cms attributes in the site's HTML; a missing key means "use the page's own text".
CREATE TABLE site_content (
    content_key VARCHAR(120) PRIMARY KEY,
    pt VARCHAR(4000),
    en VARCHAR(4000),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

-- Images uploaded through the staff panel (photos for pages), kept in the database like event posters.
CREATE TABLE media_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(30) NOT NULL,
    data BYTEA NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
