-- Photos shown on the gallery page, in display order. image_url is an https address or an uploaded file (/api/media/{id}).
CREATE TABLE gallery_photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(500) NOT NULL,
    category VARCHAR(12) NOT NULL,
    size VARCHAR(8) NOT NULL,
    caption_pt VARCHAR(120) NOT NULL,
    caption_en VARCHAR(120),
    position INTEGER NOT NULL,
    visible BOOLEAN NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT chk_gallery_category CHECK (category IN ('SPACES', 'EVENTS')),
    CONSTRAINT chk_gallery_size CHECK (size IN ('NORMAL', 'WIDE', 'TALL'))
);
CREATE INDEX idx_gallery_photos_position ON gallery_photos (position);

-- The photos that were hard-coded in gallery.html, so switching to managed photos changes nothing for visitors.
INSERT INTO gallery_photos (image_url, category, size, caption_pt, position, visible, created_at) VALUES ('https://static.wixstatic.com/media/f436ca_d9fb55418bc34b64a73f395579f6d962~mv2.jpg', 'SPACES', 'WIDE', 'South Beach · Espaço', 1, TRUE, CURRENT_TIMESTAMP);
INSERT INTO gallery_photos (image_url, category, size, caption_pt, position, visible, created_at) VALUES ('https://static.wixstatic.com/media/f436ca_6e6045974ba941aa87ae381055ee0fb2~mv2.jpg', 'EVENTS', 'NORMAL', 'Smany Friends & Sessions', 2, TRUE, CURRENT_TIMESTAMP);
INSERT INTO gallery_photos (image_url, category, size, caption_pt, position, visible, created_at) VALUES ('https://static.wixstatic.com/media/f436ca_48e7c35fae274e959019ced8fc39a1af~mv2.jpg', 'EVENTS', 'NORMAL', 'Mi Casa Winter Edition', 3, TRUE, CURRENT_TIMESTAMP);
INSERT INTO gallery_photos (image_url, category, size, caption_pt, position, visible, created_at) VALUES ('https://static.wixstatic.com/media/f436ca_81f72fe3031646ff8c075e6236667729~mv2.jpg', 'SPACES', 'TALL', 'Restaurante', 4, TRUE, CURRENT_TIMESTAMP);
INSERT INTO gallery_photos (image_url, category, size, caption_pt, position, visible, created_at) VALUES ('https://static.wixstatic.com/media/f436ca_0df16447a06a42d0b9b1a8592bd77a57~mv2.jpg', 'EVENTS', 'NORMAL', 'Mi Casa', 5, TRUE, CURRENT_TIMESTAMP);
INSERT INTO gallery_photos (image_url, category, size, caption_pt, position, visible, created_at) VALUES ('https://static.wixstatic.com/media/f436ca_6659c6cd8c5e4671ac5554b42cc7c60e~mv2.jpg', 'EVENTS', 'NORMAL', '6.º Aniversário', 6, TRUE, CURRENT_TIMESTAMP);
INSERT INTO gallery_photos (image_url, category, size, caption_pt, position, visible, created_at) VALUES ('https://static.wixstatic.com/media/f436ca_42ce4777f82d4b3bacf656ccabd66136~mv2.jpg', 'SPACES', 'NORMAL', 'Beach Bar', 7, TRUE, CURRENT_TIMESTAMP);
INSERT INTO gallery_photos (image_url, category, size, caption_pt, position, visible, created_at) VALUES ('https://static.wixstatic.com/media/f436ca_72fb9b9281e1482d9c4f982871654687~mv2.jpg', 'EVENTS', 'NORMAL', 'Sandsation', 8, TRUE, CURRENT_TIMESTAMP);
INSERT INTO gallery_photos (image_url, category, size, caption_pt, position, visible, created_at) VALUES ('https://static.wixstatic.com/media/f436ca_c0d253b3df724e429ba21d72cba5ff70~mv2.jpg', 'EVENTS', 'WIDE', 'Réveillon', 9, TRUE, CURRENT_TIMESTAMP);
